# Generated by Django 2.2.7 on 2020-08-17 22:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('zoom', models.DecimalField(decimal_places=25, max_digits=50)),
                ('center', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=25, max_digits=50), size=2)),
                ('extent', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=25, max_digits=50), size=4)),
            ],
        ),
    ]
